CampusConnectHub/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('Account.urls')),
    path('forum/',include("Forum.urls")),
    path('event/',include("Event.urls")),
    path('', views.home,name='home'),
    path('community/',include("Community.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Community/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.community,name="community"),
    path('room/<str:pk>',views.room,name="room"),
    
    path('create-room',views.createRoom,name="create-room"),
    path('update-room/<str:pk>',views.updateRoom,name="update-room"),
    path('join-room/<str:pk>/', views.join_room, name='join-room'),
    path('delete-room/<str:pk>',views.deleteRoom,name="delete-room"),
    path('delete-message/<str:pk>',views.deleteMessage,name="delete-message"),
    path('update_message/<str:pk>/', views.update_message, name='update_message'),
    path('delete_message/<str:pk>/', views.deleteMessage, name='delete_message'),
    path('leave-room/<str:pk>',views.leave_room,name="leave-room"),
    path('join/<str:unique_id>/', views.join_room_by_id, name='join_room_by_id'),
    
]

Event/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
   path("",views.event,name="event"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Community/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from PIL import Image
# Create your models here.

class Topic(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participant = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default="default.jpg", upload_to="server_profile")
    unique_id = models.CharField(max_length=6, default=uuid.uuid4().hex[:6], unique=True)  

    class Meta:
        ordering = ['-updated', '-created']
        
    def __str__(self):
        return self.name
    
    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if(img.height > 300 or img.width > 300):
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)
    
    
    

class Message(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-updated','-created']
        
    def __str__(self):
        return self.body[0:50]
    
    

Community/forms.py
from django import forms
from .models import Room

class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['name', 'description', 'image']
        

Community/views.py
import json
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.db.models import Q
from . models import Room,Topic,Message
from . forms import RoomForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.utils import timezone
import uuid


@login_required(login_url='login')
def community(request):
    q = request.GET.get('q', '')
    topic_name = request.GET.get('topic', '')  # Get the selected topic from query parameters

    rooms = Room.objects.filter(Q(topic__name__icontains=q) | Q(name__icontains=q) | Q(description__icontains=q))
    
    # logged = request.user
    
    # for room in rooms:
    #     if logged in room.participant.all():
    #         print(True)
    
    
    logged_user = request.user
    
    # Retrieve the rooms (communities) that the user has joined
    joined_rooms = Room.objects.filter(participant=logged_user)
    
    # Retrieve the recent messages for the joined rooms
    recent_messages = Message.objects.filter(room__in=joined_rooms)


    
    # Filter rooms based on the selected topic
    if topic_name and topic_name != 'all':
        rooms = rooms.filter(topic__name__icontains=topic_name)

    topics = Topic.objects.all()
    room_count = rooms.count()
        

    recent_activity = Message.objects.filter(Q(room__topic__name__icontains=q))
    
    
    
    return render(request, "Community/community.html", {'rooms': rooms, 'topics': topics, 'room_count': room_count, 'recent_activity': recent_activity,'recent_messages':recent_messages})


@login_required(login_url='')
def room(request, pk):
    room = Room.objects.get(id=pk)
    print(room.host)
    user_rooms = Room.objects.filter(participant=request.user)
    room_messages = room.message_set.all().order_by('-created')
    participants = room.participant.all()

    if request.method == "POST":
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        room.participant.add(request.user)
        return redirect('room', pk=room.id)

    context = {'room': room, 'room_messages': room_messages, 'participants': participants,'user_rooms':user_rooms}
    return render(request, 'Community/ChatRoom.html', context)



@login_required
def join_room(request, pk):
    room = Room.objects.get(id=pk)
    if request.user not in room.participant.all():
        room.participant.add(request.user)
    return redirect(reverse('community') + '?joined_successfully=True')

@login_required(login_url='login')
def createRoom(request):
    topics = Topic.objects.all()
    if request.method == 'POST':
        form = RoomForm(request.POST, request.FILES)
        print(request.POST)
        if form.is_valid():
            room = form.save(commit=False)
            room.host = request.user
            room.unique_id = uuid.uuid4().hex[:6]
            topic_name = request.POST.get('topic')
            topic, created = Topic.objects.get_or_create(name=topic_name)
            if topic is not None:
                room.topic = topic
            uploaded_image = form.cleaned_data['image']
            room.image = uploaded_image
            room.save()  # Save the room object first
            room.participant.add(request.user)  # Set the many-to-many relationship after saving
            return redirect('community')

    else:
        form = RoomForm()
    return render(request, 'Community/createcommunity.html', {'form': form, 'topics': topics})




@login_required(login_url='login')
def join_room_by_id(request, unique_id):
    room = Room.objects.filter(unique_id=unique_id).first()
    if room:
        if request.user not in room.participant.all():
            room.participant.add(request.user)
        return redirect('room', pk=room.id)  # Redirect to the room page
    else:
        # Handle invalid unique IDs
        return HttpResponse("Room not found or expired.")   
    
@login_required(login_url='login')
def updateRoom(request, pk):
    # Retrieve the room object by its ID
    room = get_object_or_404(Room, id=pk)
    topics = Topic.objects.all()

    if request.method == 'POST':
        form = RoomForm(request.POST, request.FILES, instance=room)
        if form.is_valid():
            # Retrieve the updated topic from the form data
            topic_name = request.POST.get('topic')
            topic, created = Topic.objects.get_or_create(name=topic_name)
            
            # Set the updated topic on the room object
            room.topic = topic

            form.save()  # Save the updated room
            return redirect('community')  # Redirect to some URL after room update
   
    else:
        # If it's a GET request, initialize the form with existing room data
        form = RoomForm(instance=room)

    return render(request, 'Community/updatecommunity.html', {'form': form, 'room':room,'topics': topics})



@login_required(login_url='login')
def deleteRoom(request, pk):
    room = get_object_or_404(Room, pk=pk)
    # print("hello")
    # print("------------")
    if request.user != room.host:
        return HttpResponse('You are not allowed here')
    
    if request.method == 'POST':
        # print("hello")
        if request.user == room.host:
            room.delete()
            # print("hello")
            messages.success(request, 'Question deleted successfully.')
            return redirect('community')
        else:
            messages.error(request, 'You are not authorized to delete this question.')
            return redirect(reverse('room', kwargs={'pk': pk}))
    
    return redirect('home')  

@login_required(login_url='login')
def deleteMessage(request,pk):
    message = get_object_or_404(Message,pk=pk)
    message.delete()
    return JsonResponse({'message': 'Message deleted successfully'})

@login_required(login_url='login')
def update_message(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        return HttpResponse('You are not allowed here')
    
    #  # Print the request method (e.g., GET or POST)
    # print("Request method:", request.method)

    # # Print the request body
    # print("Request body:", request.body)

    if request.method == "POST":
        
        json_data = json.loads(request.body.decode('utf-8'))
        
        # Extract the new message body directly
        new_message_body = json_data['new_message_body'].strip()  # Remove leading/trailing whitespace if needed

        # Update the message body with the new message body
        message.body = new_message_body
        message.save()
        return JsonResponse({'success': True})  # Respond with a JSON success message
    

    return JsonResponse({'error': 'Invalid request'}) 


@login_required
def leave_room(request, pk):
    user = request.user
    room = get_object_or_404(Room, pk=pk)
    
    # Remove user from the room participants
    if user in room.participant.all():
        room.participant.remove(user)
        room.save()
        
        # Delete user's messages in the room
        Message.objects.filter(room=room, user=user).delete()
        
        return redirect('community')  
    else:
        return HttpResponse("You are not a participant of this room.")
    



    

Community/templates/Community/Create_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="css/main.css" />
</head>

<body>
    <!-- Nav bar -->

    <nav class="bg-white border-gray-200 dark:bg-gray-900">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse">
                <img src="img/herald-white-logo.png" class="h-8" alt="Flowbite Logo" />
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white"></span>
            </a>
            <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
                <button type="button"
                    class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
                    id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown"
                    data-dropdown-placement="bottom">
                    <span class="sr-only">Open user menu</span>
                    <img class="w-8 h-8 rounded-full" src="{% static 'img/user-1.jpg'%}" alt="user photo">
                </button>
                <!-- Dropdown menu -->
                <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600"
                    id="user-dropdown">
                    <div class="px-4 py-3">
                        <span class="block text-sm text-gray-900 dark:text-white">Bonnie Green</span>
                        <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">name@flowbite.com</span>
                    </div>
                    <ul class="py-2" aria-labelledby="user-menu-button">
                        <li>
                            <a href="#"
                                class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Dashboard</a>
                        </li>
                        <li>
                            <a href="#"
                                class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Settings</a>
                        </li>
                        <li>
                            <a href="#"
                                class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Earnings</a>
                        </li>
                        <li>
                            <a href="#"
                                class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign
                                out</a>
                        </li>
                    </ul>
                </div>
                <button data-collapse-toggle="navbar-user" type="button"
                    class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                    aria-controls="navbar-user" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 17 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M1 1h15M1 7h15M1 13h15" />
                    </svg>
                </button>
            </div>
            <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
                <ul
                    class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                    <li>
                        <a href="index.html"
                            class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500"
                            aria-current="page">Home</a>
                    </li>
                    <li>
                        <a href="#"
                            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
                    </li>
                    <li>
                        <a href="#"
                            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Services</a>
                    </li>
                    <li>
                        <a href="#"
                            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Pricing</a>
                    </li>
                    <li>
                        <a href="#"
                            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="w-screen h-screen bg-cover bg-center overflow-hidden" style="background-image: url('static/img/bannar4.jpg');">
        <div class="p-0 md:p-8 static">

            <div class="content text-white absolute top-1/2 transform -translate-y-1/2 ml-5 z-20">

                <div class="launch-time flex space-x-4">

                    <div class="relative text-bold">
                        <p id="days" class="mt-100 text-9xl font-bold">00</p>
                        <span
                        class="absolute bottom-3 left-3/4 transform -translate-x-1/10 -translate-y-1/6 rotate-90 text-3xl font-extrabold">
                        Days
                    </span>
                    
                    </div>

                    <div class="relative text-bold">
                        <p id="hours" class="text-9xl font-bold">00</p>
                        <span
                        class="absolute bottom-6 left-1/2 transform -translate-x-1/10 -translate-y-1/6 rotate-90 text-3xl font-extrabold">
                        Hours
                    </span>
                    </div>

                    <div class="relative text-bold">
                        <p id="minutes" class="text-9xl font-bold">00</p>
                        <span
                            class="absolute bottom-6 left-1/2 transform -translate-x-1/10 -translate-y-1/6 rotate-90 text-3xl font-extrabold">
                            Mins
                        </span>
                    </div>

                    <div class="relative text-bold">
                        <p id="seconds" class="text-9xl font-bold">00</p>
                        <span
                            class="absolute bottom-6 left-1/2 transform -translate-x-1/10 -translate-y-1/6 rotate-90 text-3xl font-extrabold">
                            Secs
                        </span>
                    </div>

                </div>
                <br>
                <br>
                <h1 class="text-7xl font-bold">Conference <span class="text-[#ff3753]">2023</span></h1>
                <p class="Address text-5xl font-bold">LT-01 Wolverhampton Block</p>

                <button type="button"
                    class="bg-transparent border-2 border-white py-2 px-4 mt-5 flex items-center text-white hover:bg-white hover:text-black transition duration-300">
                    Learn More <img src="images/triangle.png" class="w-4 ml-2">
                </button>
            </div>

            <img src="images/rocket.png" class="rocket w-64 absolute right-10 bottom-0 animate-rocket" alt="Rocket">


        </div>
    </div>


</body>

</html>

Community/templates/Community/activity_component.html
<h3> Recent Activity </h3>
<hr>

{% for activity in recent_activity%}

<div>
  <small>@ {{activity.user}} {{activity.created|timesince}}</small>
  <small> replied to"{{activity.room}}</small>
  <p>{{activity}}</p>
  {% if request.user == activity.user %}
  <a href="{% url 'delete-message' activity.id %}">Delete</a>
  {% endif %}
  <hr>
</div>
{% endfor%}

Community/templates/Community/community.html
{% extends 'Forum/base.html' %}
{% load static %}

{% block content %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

<div class="flex">

    <div class="w-1/5 bg-gray-900">
        <h1 class="text-1xl text-gray-700 ml-9 mt-5 font-semibold"> BROWSE TOPICS</h1>
        <ul class="">
            <li>
                <a href=""
                    class="flex ml-9 mt-4 mb-4 text-lg justify-between items-center text-gray-500 transition duration-300 ease-in-out font-bold hover:text-blue-500">
                    <span class="mt-2 ">All</span>
                    <span class="bg-dark py-2 px-4 text-white font-semibold">{{ room_count }}</span>
                </a>
            </li>

            {% for topic in topics %}
            <li>
                <a href=""
                    class="flex ml-9 mt-4 mb-4 text-lg justify-between items-center text-gray-500 transition duration-300 ease-in-out font-bold hover:text-blue-500">
                    <span class="mt-2">{{topic.name}}</span>
                    <span class="bg-dark py-2 px-4 text-white font-semibold">{{ topic.room_set.count }}</span>
                </a>
            </li>
            {% endfor %}


        </ul>
    </div>


    <div class="w-3/5 ml-2 bg-gray-900">

        <div class="flex ">

            <div>
                <h1 class="text-1xl text-gray-300 ml-9 mt-5 font-semibold"> ROOMS</h1>
                <h1 class="text-1xl text-gray-400 ml-9 mt-1"> {{room_count}} Rooms Available</h1>
            </div>

            <div class="flex-shrink-0 ml-auto">
                <a href="{% url 'create-room' %}">
                    <button type="button"
                        class="text-white mt-5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
                        Create Room
                    </button>
                </a>
            </div>



        </div>

        <div>
            <h1 class="text-1xl text-gray-700 ml-9 mt-5 font-bold text-cyan-400 text-lg">All Rooms</h1>

            {% for room in rooms %}
            <div class="rounded-lg bg-gray-800 ml-9 mt-5 p-4 w-4/5 h-auto flex flex-col">
                <!-- User Profile Image -->
                <div class="flex w-full">
                    <img src="{{room.host.profile.image.url}}" alt="User Profile"
                        class="w-11 h-11 rounded-full border-cyan-400 border-2">
                    <!-- Username and Date -->
                    <div class="ml-2 flex flex-grow justify-between">
                        <div class="font-semibold text-slate- mt-2 text-lg text-cyan-400">Host
                            @{{room.host.username}}</div>
                        <div class="text-gray-400 font-semibold mt-2">on {{room.created | date:"F j, Y" }}</div>
                    </div>
                </div>

                {% if request.user in room.participant.all %}
                <h1 class="text-2xl p-1 my-3 font-semibold text-gray-300"> <a href="{% url 'room' room.id %}">{{room.name }}</a></h1>
                {% else %}
                <h1 class="text-2xl p-1 my-3 font-semibold text-gray-300"> {{ room.name }} <i class="fas fa-lock" style="margin-left: 10px;" ></i></h1>

                {% endif %}



                <p class="ml-1 text-gray-300 font-normal">{{room.description}}</p>
                <br>

                <div class="flex justify-start ml-1">
                    {% for participant in room.participant.all|slice:":5" %}
                    <img src="{{ participant.profile.image.url }}" alt="User Profile"
                        class="w-10 h-10 rounded-full border-cyan-400 border-2 mr-2">
                    {% endfor %}
                </div>

                <br>
                <hr>
                <br>
                <div class="flex justify-between items-center">
                    <ul class="anser-list flex space-x-10">
                        <li>
                            <!-- SVG icon -->
                            <svg class="inline-block h-4 w-4 mb-1 mr-1 text-cyan-400" xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 32 32" fill="currentColor">
                                <title>User Group</title>
                                <!-- Include the path data here -->
                                <path
                                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                                </path>
                                <path
                                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                                </path>
                                <path
                                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                                </path>
                                <path
                                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                                </path>
                            </svg>
                            <!-- Text -->
                            <a href="polls.html" class="text-gray-400 font-semibold">{{room.participant.count}}</a>

                            <a href="most-answered.html"
                                class="border border-cyan-400 text-cyan-400 font-normal py-2 px-4 ml-2 rounded-full inline-block transition duration-300">
                                {{room.topic.name}}
                            </a>

                        </li>
                    </ul>
                    <!-- Added Join button -->
                    {% if request.user in room.participant.all %}
                    <!-- User is joined -->
                    <a href="most-answered.html"
                        class="border border-cyan-400 text-cyan-400 font-normal py-2 px-4 ml-2 rounded-full inline-block transition duration-300">
                        Joined
                    </a>
                    {% else %}
                    <!-- User is not joined -->
                    <a href="{% url 'join-room' room.id %}">
                        <button type="button"
                            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Join</button>
                    </a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}



            <br>
            <br>
            

            <div class="flex justify-center mt-5 mr-14">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        {% if questions.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1">First</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ questions.previous_page_number }}">Previous</a>
                        </li>
                        {% endif %}
                        {% for num in questions.paginator.page_range %}
                        <li class="page-item {% if num == questions.number %}active{% endif %}">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                        {% endfor %}
                        {% if questions.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ questions.next_page_number }}">Next</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ questions.paginator.num_pages }}">Last</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>

            <br>





        </div>



    </div>

    <div class="w-1/5 bg-gray-900 mr-5 mt-5">
        <div class="rounded-lg bg-gray-800 ml-9 mt-5 h-auto flex flex-col">
            <div class="bg-gray-700 h-10 rounded-t-lg">
                <div class="items-center ml-2 mt-1">
                    <h1 class="text-cyan-400 font-semibold text-lg">Server Messages</h1>
                </div>
            </div>
            <div class="p-4">
                {% for message in recent_messages|slice:":5" %}
                <!-- Server message -->
                <div class="bg-gray-700 rounded-lg p-3 mb-3" style="max-width: 400px;"> <!-- Adjust max-width as needed -->
                    <div class="flex items-center">
                        <div class="w-10 h-10 rounded-full flex-shrink-0 flex justify-center items-center mr-3 mb-5">
                            <img src="{{ message.room.image.url }}" alt="Server Logo" class="w-full h-full rounded-full">
                        </div>
                        <div style="max-width: 300px; overflow-wrap: break-word;">
                            <span class="text-cyan-400 font-semibold">@{{ message.room.name }}</span><br>
                            <span class="text-gray-500 font-semibold">{{ message.created|timesince }} ago</span><br>
                            <p class="text-gray-400 font-semibold text-justify " style="width: 200px;">{{ message.body}}</p>
                        </div>
                    </div>
                </div>
                
                
                {% endfor %}
            </div>
        </div>
    </div>
    
  





</div>

{% if request.GET.joined_successfully %}
    <script>
        window.onload = function() {
            alert("Joined successfully!");
        };
    </script>
{% endif %}

{% endblock %}